"""Policy: agent nào được dùng tool nào. LLM không được tự ý gọi tool khác."""
from __future__ import annotations

# 4 copilot theo thiết kế. Tool ghi nguy hiểm luôn needs_approval ở registry.
POLICY: dict[str, list[str]] = {
    "student": [
        "search_courses",
        "get_course_outline",
        "get_lesson_context",
        "get_my_progress",
        "get_my_mastery",
        "record_feedback_correction",
        "remember_user_fact",
        "recall_user_facts",
        "forget_user_fact",
        "enroll_course",
        "mark_lesson_complete",
        "save_note",
        "create_review_set",
        "schedule_review",
        "set_goal",
        "start_session",
        "navigate",
        "render_view",
    ],
    "teacher": [
        "search_courses",
        "get_course_outline",
        "get_lesson_context",
        "get_batch_progress",
        "list_at_risk_students",
        "get_student_mastery",
        "draft_quiz",
        "draft_assignment_feedback",
        "remember_user_fact",
        "recall_user_facts",
        "forget_user_fact",
        "message_students",
        "create_live_class",
        "publish_lesson_draft",
        "analyze_course_gaps",
        "get_course_authoring_state",
        "manage_course",
        "manage_chapter",
        "manage_lesson",
        "manage_quiz",
        "manage_lesson_block",
        "manage_assignment",
        "manage_programming_exercise",
        "navigate",
        "render_view",
    ],
    "evaluator": [
        "get_assignment_submissions",
        "get_quiz_submissions",
        "draft_assignment_feedback",
        "get_my_mastery",
        "remember_user_fact",
        "recall_user_facts",
        "forget_user_fact",
        "navigate",
        "render_view",
    ],
    "admin": [
        "search_courses",
        "get_course_outline",
        "get_lesson_context",
        "get_batch_progress",
        "list_at_risk_students",
        "get_student_mastery",
        "update_course_content_after_approval",
        "message_students",
        "create_live_class",
        "publish_lesson_draft",
        "analyze_course_gaps",
        "get_course_authoring_state",
        "manage_course",
        "manage_chapter",
        "manage_lesson",
        "manage_quiz",
        "manage_assignment",
        "manage_lesson_block",
        "manage_programming_exercise",
        "remember_user_fact",
        "recall_user_facts",
        "forget_user_fact",
        "navigate",
        "render_view",
    ],
}


def allowed_tools(role: str) -> list[str]:
    return POLICY.get(role, POLICY["student"])
